SELECT *,
       FIRST_VALUE(Sales) OVER (PARTITION BY state ORDER BY Date) AS first_day_sales,
       LAST_VALUE(Sales) OVER (PARTITION BY state ORDER BY Date ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS last_day_sales,
       FIRST_VALUE(Sales) OVER (PARTITION BY state ORDER BY Date ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS diff_from_first_day_sales
FROM dbo.player;
